FROM php:8.2-fpm

WORKDIR /var/www/html

# Instalar dependencias del sistema necesarias para Symfony
RUN apt-get update && apt-get install -y \
    git unzip libicu-dev libzip-dev libpng-dev libonig-dev \
    && docker-php-ext-install pdo pdo_mysql intl zip gd

# Copiar composer desde imagen oficial
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Permitir plugins aunque sea root
ENV COMPOSER_ALLOW_SUPERUSER=1

CMD ["php-fpm"]

